language: swift
osx_image: xcode10.1
script:
- xcodebuild -workspace SafeBrowsing.xcworkspace -scheme SafeBrowsing -destination "platform=iOS
  Simulator,name=iPhone XS,OS=12.1" -configuration Debug -enableCodeCoverage YES clean
  build test
after_success:
- bash <(curl -s https://codecov.io/bash)